#pragma once

// Given a verified symmetry::group (state-permutation generators for the game
// automaton), partition automaton states into SHARED states (fixed by every
// generator) and CLIENT-BLOCK "slots": B blocks of size n = |indices|
// (number of clients), with a consistent per-client slot identity across
// blocks -- this is exactly the (shared, client-owned-coordinate) split
// symmetric_downset.hh's count_vector needs (DIAGNOSIS.md, "Symmetry
// reduction: design + status").
//
// Consistency (why "slot" identity across DIFFERENT blocks is well-defined):
// two client-block states s (in block i) and s' (in block j != i) are the
// SAME client slot iff they have the exact same STABILIZER -- the same
// subset of `gens` fixing them. This is the correct characterization
// precisely because every generator here originates from a single AP-level
// client-index transposition applied UNIFORMLY across the whole automaton
// (by construction in symmetry::detect), so the generating group acts
// "diagonally" -- the same abstract permutation on every block. We VERIFY
// this structural assumption at runtime (every block must have exactly one
// state per distinct stabilizer-signature, matching every other block) and
// conservatively return std::nullopt ("not usable") if it doesn't hold,
// rather than silently mislabeling -- fewer exploitable symmetries is always
// sound, mislabeling would not be.

#include "solver/symmetry.hh"

#include <algorithm>
#include <cstdint>
#include <functional>
#include <map>
#include <optional>
#include <vector>

namespace symmetry {

  struct block_layout {
      unsigned num_states = 0;
      unsigned num_clients = 0;   // n
      unsigned num_blocks = 0;    // B
      std::vector<int> block_of;  // block_of[state] in [0,B), or -1 if shared
      std::vector<int> slot_of;   // slot_of[state] in [0,n), or -1 if shared
      std::vector<std::vector<unsigned>> block_slot_state;  // [block][slot] -> automaton state
      std::vector<unsigned> shared_states;                  // sorted, deterministic order
  };

  namespace detail {
    // Union-find orbits of {0..num_states-1} under the group generated by `gens`.
    inline std::vector<unsigned> compute_orbit_roots (
        const std::vector<std::vector<unsigned>>& gens, unsigned num_states) {
      std::vector<unsigned> parent (num_states);
      for (unsigned i = 0; i < num_states; ++i) parent[i] = i;
      std::function<unsigned (unsigned)> find = [&] (unsigned x) {
        while (parent[x] != x) { parent[x] = parent[parent[x]]; x = parent[x]; }
        return x;
      };
      auto unite = [&] (unsigned a, unsigned b) {
        a = find (a);
        b = find (b);
        if (a != b) parent[a] = b;
      };
      for (const auto& g : gens)
        for (unsigned s = 0; s < num_states; ++s)
          unite (s, g[s]);
      std::vector<unsigned> root (num_states);
      for (unsigned s = 0; s < num_states; ++s) root[s] = find (s);
      return root;
    }
  }  // namespace detail

  inline std::optional<block_layout> compute_block_layout (const group& G, unsigned num_states) {
    if (not G.full_symmetric or G.gens.empty ())
      return std::nullopt;
    const unsigned n = (unsigned) G.indices.size ();
    // Slot identity is recovered via each state's stabilizer signature (which
    // generators fix it) -- provably a UNIQUE identifier per client for n>=3
    // (client k's stabilizer is exactly "every transposition not involving
    // k", a distinct subgroup for each k). This degenerates for n==2: the
    // single (0,1) generator moves BOTH slots, so neither has a
    // distinguishing signature ("fixed by no generator" for both). n==2 is
    // not the case this optimization targets (the antichain blowup needing
    // symmetry reduction only appears for n>=5ish clients; see DIAGNOSIS.md),
    // so we conservatively decline rather than build a fragile tie-break.
    if (n < 3)
      return std::nullopt;

    auto root = detail::compute_orbit_roots (G.gens, num_states);
    std::map<unsigned, std::vector<unsigned>> orbit_members;
    for (unsigned s = 0; s < num_states; ++s)
      orbit_members[root[s]].push_back (s);

    block_layout L;
    L.num_states = num_states;
    L.num_clients = n;
    L.block_of.assign (num_states, -1);
    L.slot_of.assign (num_states, -1);

    std::vector<std::vector<unsigned>> blocks;
    for (auto& [r, members] : orbit_members) {
      if (members.size () == 1)
        L.shared_states.push_back (members[0]);
      else if (members.size () == n)
        blocks.push_back (members);
      else
        return std::nullopt;  // orbit size neither 1 nor n: unexpected structure, bail
    }
    std::sort (L.shared_states.begin (), L.shared_states.end ());
    L.num_blocks = (unsigned) blocks.size ();
    if (L.num_blocks == 0)
      return std::nullopt;  // no client-block coordinates to exploit

    // Per-state stabilizer signature (as a bitmask over generator index): the
    // set of verified generators that fix this state.
    auto signature = [&] (unsigned s) {
      std::vector<bool> sig (G.gens.size ());
      for (size_t i = 0; i < G.gens.size (); ++i)
        sig[i] = (G.gens[i][s] == s);
      return sig;
    };

    // Fix the canonical slot order via block 0 (deterministic: sorted by
    // automaton state index).
    std::vector<unsigned> ref = blocks[0];
    std::sort (ref.begin (), ref.end ());
    std::vector<std::vector<bool>> ref_sig (n);
    for (unsigned k = 0; k < n; ++k)
      ref_sig[k] = signature (ref[k]);
    for (unsigned k = 0; k < n; ++k)
      for (unsigned k2 = k + 1; k2 < n; ++k2)
        if (ref_sig[k] == ref_sig[k2])
          return std::nullopt;  // reference block itself isn't cleanly separated: bail

    L.block_slot_state.assign (L.num_blocks, std::vector<unsigned> (n, (unsigned) -1));
    for (unsigned b = 0; b < L.num_blocks; ++b) {
      for (unsigned s : blocks[b]) {
        const auto sig = signature (s);
        int matched_slot = -1;
        for (unsigned k = 0; k < n; ++k)
          if (sig == ref_sig[k]) { matched_slot = (int) k; break; }
        if (matched_slot == -1 or L.block_slot_state[b][matched_slot] != (unsigned) -1)
          return std::nullopt;  // no unique matching slot: bail
        L.block_slot_state[b][matched_slot] = s;
        L.block_of[s] = (int) b;
        L.slot_of[s] = matched_slot;
      }
      for (unsigned k = 0; k < n; ++k)
        if (L.block_slot_state[b][k] == (unsigned) -1)
          return std::nullopt;  // some slot unfilled in this block: bail
    }
    return L;
  }

}  // namespace symmetry
