#pragma once

#ifndef ACACIA_COMPILE_ALL_COMPONENTS
# define ACACIA_COMPILE_ALL_COMPONENTS 0
#endif

#ifndef ACACIA_COMPILE_AUT_PREPROCESSOR_NO_PREPROCESSING
# define ACACIA_COMPILE_AUT_PREPROCESSOR_NO_PREPROCESSING \
  (ACACIA_COMPILE_ALL_COMPONENTS || ACACIA_ENABLE_AUT_PREPROCESSOR_NO_PREPROCESSING)
#endif
#ifndef ACACIA_COMPILE_AUT_PREPROCESSOR_STANDARD
# define ACACIA_COMPILE_AUT_PREPROCESSOR_STANDARD \
  (ACACIA_COMPILE_ALL_COMPONENTS || ACACIA_ENABLE_AUT_PREPROCESSOR_STANDARD)
#endif
#ifndef ACACIA_COMPILE_AUT_PREPROCESSOR_SURELY_LOSING
# define ACACIA_COMPILE_AUT_PREPROCESSOR_SURELY_LOSING \
  (ACACIA_COMPILE_ALL_COMPONENTS || ACACIA_ENABLE_AUT_PREPROCESSOR_SURELY_LOSING)
#endif
#ifndef ACACIA_COMPILE_AUT_PREPROCESSOR_ELEVATOR
# define ACACIA_COMPILE_AUT_PREPROCESSOR_ELEVATOR \
  (ACACIA_COMPILE_ALL_COMPONENTS || ACACIA_ENABLE_AUT_PREPROCESSOR_ELEVATOR)
#endif

#ifndef ACACIA_COMPILE_BOOLEAN_STATES_FORWARD_SATURATION
# define ACACIA_COMPILE_BOOLEAN_STATES_FORWARD_SATURATION \
  (ACACIA_COMPILE_ALL_COMPONENTS || ACACIA_ENABLE_BOOLEAN_STATES_FORWARD_SATURATION)
#endif
#ifndef ACACIA_COMPILE_BOOLEAN_STATES_NO_BOOLEAN_STATES
# define ACACIA_COMPILE_BOOLEAN_STATES_NO_BOOLEAN_STATES \
  (ACACIA_COMPILE_ALL_COMPONENTS || ACACIA_ENABLE_BOOLEAN_STATES_NO_BOOLEAN_STATES)
#endif

#ifndef ACACIA_COMPILE_BOOLEAN_STATES_TRANSITION_CORE
# define ACACIA_COMPILE_BOOLEAN_STATES_TRANSITION_CORE \
  (ACACIA_COMPILE_ALL_COMPONENTS || ACACIA_ENABLE_BOOLEAN_STATES_TRANSITION_CORE)
#endif

#ifndef ACACIA_COMPILE_IOS_PRECOMPUTER_DELEGATE
# define ACACIA_COMPILE_IOS_PRECOMPUTER_DELEGATE \
  (ACACIA_COMPILE_ALL_COMPONENTS || ACACIA_ENABLE_IOS_PRECOMPUTER_DELEGATE)
#endif
#ifndef ACACIA_COMPILE_IOS_PRECOMPUTER_FAKE_VARS
# define ACACIA_COMPILE_IOS_PRECOMPUTER_FAKE_VARS \
  (ACACIA_COMPILE_ALL_COMPONENTS || ACACIA_ENABLE_IOS_PRECOMPUTER_FAKE_VARS)
#endif
#ifndef ACACIA_COMPILE_IOS_PRECOMPUTER_POWSET
# define ACACIA_COMPILE_IOS_PRECOMPUTER_POWSET \
  (ACACIA_COMPILE_ALL_COMPONENTS || ACACIA_ENABLE_IOS_PRECOMPUTER_POWSET)
#endif
#ifndef ACACIA_COMPILE_IOS_PRECOMPUTER_STANDARD
# define ACACIA_COMPILE_IOS_PRECOMPUTER_STANDARD \
  (ACACIA_COMPILE_ALL_COMPONENTS || ACACIA_ENABLE_IOS_PRECOMPUTER_STANDARD)
#endif
#ifndef ACACIA_COMPILE_IOS_PRECOMPUTER_MONA
# define ACACIA_COMPILE_IOS_PRECOMPUTER_MONA \
  (ACACIA_COMPILE_ALL_COMPONENTS || ACACIA_ENABLE_IOS_PRECOMPUTER_MONA)
#endif
#ifndef ACACIA_COMPILE_IOS_PRECOMPUTER_SEMANTIC_MONA
# define ACACIA_COMPILE_IOS_PRECOMPUTER_SEMANTIC_MONA \
  (ACACIA_COMPILE_ALL_COMPONENTS || ACACIA_ENABLE_IOS_PRECOMPUTER_SEMANTIC_MONA)
#endif

#ifndef ACACIA_COMPILE_ACTIONER_NO_IOS_PRECOMPUTATION
# define ACACIA_COMPILE_ACTIONER_NO_IOS_PRECOMPUTATION \
  (ACACIA_COMPILE_ALL_COMPONENTS || ACACIA_ENABLE_ACTIONER_NO_IOS_PRECOMPUTATION)
#endif
#ifndef ACACIA_COMPILE_ACTIONER_STANDARD
# define ACACIA_COMPILE_ACTIONER_STANDARD \
  (ACACIA_COMPILE_ALL_COMPONENTS || ACACIA_ENABLE_ACTIONER_STANDARD)
#endif

#ifndef ACACIA_COMPILE_INPUT_PICKER_CRITICAL
# define ACACIA_COMPILE_INPUT_PICKER_CRITICAL \
  (ACACIA_COMPILE_ALL_COMPONENTS || ACACIA_ENABLE_INPUT_PICKER_CRITICAL)
#endif
#ifndef ACACIA_COMPILE_INPUT_PICKER_CRITICAL_FULLRND
# define ACACIA_COMPILE_INPUT_PICKER_CRITICAL_FULLRND \
  (ACACIA_COMPILE_ALL_COMPONENTS || ACACIA_ENABLE_INPUT_PICKER_CRITICAL_FULLRND)
#endif
#ifndef ACACIA_COMPILE_INPUT_PICKER_CRITICAL_PQ
# define ACACIA_COMPILE_INPUT_PICKER_CRITICAL_PQ \
  (ACACIA_COMPILE_ALL_COMPONENTS || ACACIA_ENABLE_INPUT_PICKER_CRITICAL_PQ)
#endif
#ifndef ACACIA_COMPILE_INPUT_PICKER_CRITICAL_RND
# define ACACIA_COMPILE_INPUT_PICKER_CRITICAL_RND \
  (ACACIA_COMPILE_ALL_COMPONENTS || ACACIA_ENABLE_INPUT_PICKER_CRITICAL_RND)
#endif
