#!/usr/bin/env python3
"""Convert a directory of TLSF files into benchmark .ltl/.part pairs."""

from __future__ import annotations

import argparse
import csv
import pathlib
import subprocess

from tlsf_pairs import convert_pair


def failure_reason(stderr: str, stdout: str) -> str:
    text = f"{stderr}\n{stdout}".strip()
    if "strong next" in text.lower() or "x[!]" in text.lower():
        return "strong next is unsupported by SyFCo's ltlxba printer"
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    return lines[-1] if lines else "SyFCo conversion failed without a diagnostic"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=pathlib.Path)
    parser.add_argument("output", type=pathlib.Path)
    parser.add_argument("--syfco", default="syfco")
    parser.add_argument(
        "--list-output",
        type=pathlib.Path,
        help="also write a benchmark .list containing every converted instance",
    )
    parser.add_argument("--target", choices=("Mealy", "Moore"),
                        help="adapt to this solver target exactly once; keep source semantics")
    parser.add_argument("--stage-timeout", type=float, default=120)
    parser.add_argument("--canonicalizer", type=pathlib.Path)
    args = parser.parse_args()

    sources = sorted(args.source.glob("*.tlsf"), key=lambda path: path.name)
    if not sources:
        raise SystemExit(f"no .tlsf files found under {args.source}")
    args.output.mkdir(parents=True, exist_ok=True)

    skipped: list[dict[str, str]] = []
    converted_names: list[str] = []
    converted = 0
    for source in sources:
        ltl = args.output / f"{source.stem}.ltl"
        part = args.output / f"{source.stem}.part"
        try:
            formula = convert_pair(args.syfco, source, part, args.stage_timeout,
                                   args.target, args.canonicalizer)
            result = subprocess.CompletedProcess([], 0, formula, "")
        except (OSError, ValueError, subprocess.SubprocessError) as error:
            result = subprocess.CompletedProcess([], 1, "", str(error))
        if result.returncode == 0:
            ltl.write_text(result.stdout.rstrip() + "\n")
            converted += 1
            converted_names.append(ltl.name)
            continue

        ltl.unlink(missing_ok=True)
        part.unlink(missing_ok=True)
        skipped.append(
            {
                "instance": source.name,
                "reason": failure_reason(result.stderr, result.stdout),
            }
        )

    skipped_path = args.output / "skipped.tsv"
    with skipped_path.open("w", newline="") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=["instance", "reason"],
            delimiter="\t",
            lineterminator="\n",
        )
        writer.writeheader()
        writer.writerows(skipped)

    print(
        f"source={len(sources)} converted={converted} skipped={len(skipped)} "
        f"output={args.output}"
    )
    print(f"wrote skip reasons to {skipped_path}")
    if args.list_output:
        args.list_output.parent.mkdir(parents=True, exist_ok=True)
        args.list_output.write_text(
            "# Generated by benchmarking/convert-tlsf-corpus.py; do not edit by hand.\n"
            f"# source={args.source} converted={converted} skipped={len(skipped)}\n"
            + "".join(f"{name}\n" for name in converted_names)
        )
        print(f"wrote {len(converted_names)} entries to {args.list_output}")
    return int(bool(skipped))


if __name__ == "__main__":
    raise SystemExit(main())
