#!/usr/bin/env python3
"""Thin manifest/order/shard driver for the broad W1 re-evaluation campaign.

Wraps run-syntcomp26-coverage.py; it runs no solver logic itself and adds no
second PAR-2 implementation. Two subcommands:

  make-shards  Partition a corpus list into N deterministic shards by a
               stable hash of the logical ID, independent of performance or
               family outcome.

  campaign     Run one (cap, epoch) leg of the opening candidate matrix across
               all shards, alternating candidate order per shard and, for
               epoch 2, starting from the reversed base order -- so within-
               epoch host drift (thermal, cache state) cannot systematically
               favor one candidate, matching the plan's balanced-order
               requirement. One solver invocation runs at a time; shards are
               processed strictly sequentially in shard order.

Every invocation of the underlying coverage runner uses --resume, so a killed
or restarted campaign leg is safe to re-launch: already-decided instances are
skipped by the wrapped tool itself, not by a second bookkeeping layer here.
"""
import argparse
import hashlib
import pathlib
import subprocess
import sys
import time

ROOT = pathlib.Path(__file__).resolve().parent.parent
COVERAGE_RUNNER = pathlib.Path(__file__).resolve().parent / "run-syntcomp26-coverage.py"


def read_instance_ids(list_path: pathlib.Path) -> list[str]:
    ids = []
    for line in list_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        ids.append(line)
    return ids


def shard_index(instance_id: str, n_shards: int) -> int:
    digest = hashlib.sha256(instance_id.encode("utf-8")).hexdigest()
    return int(digest, 16) % n_shards


def cmd_make_shards(args: argparse.Namespace) -> int:
    ids = read_instance_ids(args.list)
    if not ids:
        print(f"FAIL: {args.list} yielded no instance IDs", file=sys.stderr)
        return 1
    shards: list[list[str]] = [[] for _ in range(args.n_shards)]
    for instance_id in ids:
        shards[shard_index(instance_id, args.n_shards)].append(instance_id)
    args.out_dir.mkdir(parents=True, exist_ok=True)
    total = 0
    for i, members in enumerate(shards):
        shard_path = args.out_dir / f"shard_{i:02d}.list"
        shard_path.write_text(
            f"# generated by run-witness-sprint.py make-shards from {args.list}\n"
            f"# shard {i} of {args.n_shards}, stable sha256(id) % {args.n_shards}\n"
            + "".join(f"{instance_id}\n" for instance_id in members),
            encoding="utf-8",
        )
        total += len(members)
        print(f"shard_{i:02d}.list: {len(members)} instances")
    if total != len(ids):
        print(f"FAIL: wrote {total} total, expected {len(ids)}", file=sys.stderr)
        return 1
    print(f"OK: {len(ids)} instances into {args.n_shards} shards under {args.out_dir}")
    return 0


def parse_candidates(spec: str) -> list[tuple[str, str]]:
    pairs = []
    for item in spec.split(","):
        label, _, binpath = item.partition("=")
        if not label or not binpath:
            raise argparse.ArgumentTypeError(
                f"--candidates entries must be LABEL=BIN, got {item!r}"
            )
        pairs.append((label, binpath))
    return pairs


def cmd_campaign(args: argparse.Namespace) -> int:
    candidates = parse_candidates(args.candidates)
    epoch_base = candidates if args.epoch == 1 else list(reversed(candidates))

    shard_paths = sorted(args.shards_dir.glob("shard_*.list"))
    if not shard_paths:
        print(f"FAIL: no shard_*.list under {args.shards_dir}", file=sys.stderr)
        return 1

    args.out_dir.mkdir(parents=True, exist_ok=True)
    log_path = args.out_dir / f"campaign-cap{args.cap}-epoch{args.epoch}.log"

    def log(msg: str) -> None:
        line = f"[{time.strftime('%Y-%m-%dT%H:%M:%S')}] {msg}"
        print(line, flush=True)
        with log_path.open("a", encoding="utf-8") as f:
            f.write(line + "\n")

    log(
        f"START cap={args.cap} epoch={args.epoch} shards={len(shard_paths)} "
        f"epoch_base={[label for label, _ in epoch_base]}"
    )

    for i, shard_path in enumerate(shard_paths):
        shard_order = epoch_base if i % 2 == 0 else list(reversed(epoch_base))
        for label, binpath in shard_order:
            out_tsv = args.out_dir / f"{label}-cap{args.cap}-epoch{args.epoch}.tsv"
            solver_label = f"{label}-cap{args.cap}-epoch{args.epoch}"
            cmd = [
                sys.executable,
                str(COVERAGE_RUNNER),
                "--bin", binpath,
                "--solver-label", solver_label,
                "--list", str(shard_path),
                "--tlsf-map", str(args.tlsf_map),
                "--tlsf-corpus", str(args.tlsf_corpus),
                "--caps", str(args.cap),
                "--memory-max", args.memory_max,
                "--memory-swap-max", args.memory_swap_max,
                "--conflict-policy", "collect",
                "--collect-rusage",
                "--preset", args.preset,
                "--acacia-sha", args.acacia_sha,
                "--output", str(out_tsv),
                "--resume",
            ]
            if args.flags:
                cmd += ["--flags", args.flags]
            log(f"shard={shard_path.name} candidate={label} -> {out_tsv.name}")
            if args.dry_run:
                log("  (dry-run, not executed) " + " ".join(cmd))
                continue
            result = subprocess.run(cmd, cwd=str(ROOT))
            if result.returncode not in (0, 1):
                # 0 = clean; the coverage runner's own --conflict-policy=collect
                # exits nonzero on any collected conflict -- durable, not fatal
                # here, but a returncode outside {0,1} means the tool itself
                # crashed rather than reporting a conflict.
                log(f"  FATAL: unexpected exit {result.returncode}, aborting leg")
                return result.returncode
            log(f"  exit={result.returncode}")

    log(f"DONE cap={args.cap} epoch={args.epoch}")
    return 0


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)

    p_shard = sub.add_parser("make-shards")
    p_shard.add_argument("--list", type=pathlib.Path, required=True)
    p_shard.add_argument("--n-shards", type=int, default=24)
    p_shard.add_argument("--out-dir", type=pathlib.Path, required=True)
    p_shard.set_defaults(func=cmd_make_shards)

    p_camp = sub.add_parser("campaign")
    p_camp.add_argument("--cap", type=int, required=True, choices=[17, 120])
    p_camp.add_argument("--epoch", type=int, required=True, choices=[1, 2])
    p_camp.add_argument("--shards-dir", type=pathlib.Path, required=True)
    p_camp.add_argument("--candidates", required=True, help="LABEL=BIN[,LABEL=BIN,...] in epoch-1 canonical order")
    p_camp.add_argument("--tlsf-map", type=pathlib.Path, required=True)
    p_camp.add_argument("--tlsf-corpus", type=pathlib.Path, required=True)
    p_camp.add_argument("--memory-max", default="8G")
    p_camp.add_argument("--memory-swap-max", default="0")
    p_camp.add_argument("--preset", required=True)
    p_camp.add_argument("--acacia-sha", required=True)
    p_camp.add_argument("--flags", default="")
    p_camp.add_argument("--out-dir", type=pathlib.Path, required=True)
    p_camp.add_argument("--dry-run", action="store_true")
    p_camp.set_defaults(func=cmd_campaign)

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
