#pragma once

#if __has_include("acacia_build_config.hh")
# include "acacia_build_config.hh"
#endif

#include "utils/todo.hh"

#ifndef CPRE_AVOID_UNIONS
# define CPRE_AVOID_UNIONS 0
#endif

#ifndef ACACIA_ENABLE_SYMMETRIC_SOLVER
# define ACACIA_ENABLE_SYMMETRIC_SOLVER 0
#endif

#ifndef ACACIA_SYMMETRY_OPTIMIZE_UNIONO
# define ACACIA_SYMMETRY_OPTIMIZE_UNIONO 1
#endif

#ifndef ACACIA_SYMMETRY_UNIONO_SPIKE
# define ACACIA_SYMMETRY_UNIONO_SPIKE 0
#endif

#ifndef ACACIA_SYMMETRY_DENSE_SIMD
# define ACACIA_SYMMETRY_DENSE_SIMD ACACIA_ENABLE_SYMMETRIC_SOLVER
#endif

#ifndef ACACIA_SYMMETRY_USE_POSETS_UNION
# define ACACIA_SYMMETRY_USE_POSETS_UNION 0
#endif

#ifndef ACACIA_SYMMETRY_PROFILE
# define ACACIA_SYMMETRY_PROFILE 0
#endif

#ifndef ACACIA_ENABLE_EQUIVARIANT_SOLVER
# define ACACIA_ENABLE_EQUIVARIANT_SOLVER 0
#endif

#ifndef ACACIA_EQUIVARIANT_MAX_STATES
# define ACACIA_EQUIVARIANT_MAX_STATES 512
#endif

#ifndef ACACIA_EQUIVARIANT_MAX_OUTPUT_LETTERS
# define ACACIA_EQUIVARIANT_MAX_OUTPUT_LETTERS 4096
#endif

#ifndef ACACIA_EQUIVARIANT_MAX_ORBITS
# define ACACIA_EQUIVARIANT_MAX_ORBITS 4096
#endif

#ifndef ACACIA_EQUIVARIANT_MIN_CLIENTS
# define ACACIA_EQUIVARIANT_MIN_CLIENTS 3
#endif

#ifndef ACACIA_EQUIVARIANT_MIN_BLOCKS
# define ACACIA_EQUIVARIANT_MIN_BLOCKS 2
#endif

// Generator-fixpoint closure can be more expensive than directly sweeping a
// small input orbit.  Keep the representative/picker loop for larger groups,
// where avoiding the full orbit has the highest payoff.
#ifndef ACACIA_EQUIVARIANT_MAX_SWEEP_CLIENTS
# define ACACIA_EQUIVARIANT_MAX_SWEEP_CLIENTS 4
#endif

#ifndef ACACIA_EQUIVARIANT_EXHAUSTIVE_DETECT
# define ACACIA_EQUIVARIANT_EXHAUSTIVE_DETECT 0
#endif

#ifndef ACACIA_EQUIVARIANT_VALIDATE_FAST_RECOGNITION
# define ACACIA_EQUIVARIANT_VALIDATE_FAST_RECOGNITION 0
#endif

#ifndef ACACIA_SYMMETRY_VERBOSE_DIAGNOSTICS
# define ACACIA_SYMMETRY_VERBOSE_DIAGNOSTICS 0
#endif

#ifndef DECOMPOSE_SPEC
# define DECOMPOSE_SPEC 1
#endif

// What follows are default values overriden by self-benchmark.sh
// or your meson setup.
//
// The defaults were copied from self-benchmark.sh 21/12/2025

// Overflow WARNING: Check VECTOR_ELT_T below before changing
#ifndef DEFAULT_K
# define DEFAULT_K 99
#endif
#ifndef DEFAULT_KMIN
# define DEFAULT_KMIN 2
#endif
#ifndef DEFAULT_KINC
# define DEFAULT_KINC 3
#endif
#ifndef DEFAULT_UNREAL_X
# define DEFAULT_UNREAL_X UNREAL_X_BOTH
#endif
#ifndef DEFAULT_SPOT_FAST
# define DEFAULT_SPOT_FAST SPOT_FAST_DET
#endif
#ifndef ACACIA_TRANSLATION_PREF
# define ACACIA_TRANSLATION_PREF spot::postprocessor::Small
#endif
#ifndef ACACIA_TRANSLATION_PREFS
# define ACACIA_TRANSLATION_PREFS spot::postprocessor::Small
#endif
#ifndef ACACIA_ENABLE_REALIZABILITY_SIMPLIFIER
# define ACACIA_ENABLE_REALIZABILITY_SIMPLIFIER 1
#endif
#ifndef ACACIA_ENABLE_SYNTACTIC_BYPASS
# define ACACIA_ENABLE_SYNTACTIC_BYPASS 1
#endif
#ifndef ACACIA_ENABLE_TLSF_FRONTEND
# define ACACIA_ENABLE_TLSF_FRONTEND 0
#endif
#ifndef VECTOR_ELT_T
# define VECTOR_ELT_T signed char
#endif
// End of overflow WARNING

#ifndef SIMD_IS_MAX
# define SIMD_IS_MAX true
#endif
#ifndef AUT_PREPROCESSOR
# define AUT_PREPROCESSOR aut_preprocessors::surely_losing
#endif
#ifndef BOOLEAN_STATES
# define BOOLEAN_STATES boolean_states::forward_saturation
#endif
#ifndef IOS_PRECOMPUTER
# define IOS_PRECOMPUTER ios_precomputers::standard
#endif
#ifndef ACTIONER
# define ACTIONER actioners::standard
#endif
#ifndef INPUT_PICKER
# define INPUT_PICKER input_pickers::critical_pq
#endif

#ifndef ACACIA_ENABLE_AUT_PREPROCESSOR_NO_PREPROCESSING
# define ACACIA_ENABLE_AUT_PREPROCESSOR_NO_PREPROCESSING 0
#endif
#ifndef ACACIA_ENABLE_AUT_PREPROCESSOR_STANDARD
# define ACACIA_ENABLE_AUT_PREPROCESSOR_STANDARD 0
#endif
#ifndef ACACIA_ENABLE_AUT_PREPROCESSOR_SURELY_LOSING
# define ACACIA_ENABLE_AUT_PREPROCESSOR_SURELY_LOSING 1
#endif
#ifndef ACACIA_ENABLE_AUT_PREPROCESSOR_ELEVATOR
# define ACACIA_ENABLE_AUT_PREPROCESSOR_ELEVATOR 0
#endif

#ifndef ACACIA_ENABLE_BOOLEAN_STATES_FORWARD_SATURATION
# define ACACIA_ENABLE_BOOLEAN_STATES_FORWARD_SATURATION 1
#endif
#ifndef ACACIA_ENABLE_BOOLEAN_STATES_NO_BOOLEAN_STATES
# define ACACIA_ENABLE_BOOLEAN_STATES_NO_BOOLEAN_STATES 0
#endif

#ifndef ACACIA_ENABLE_IOS_PRECOMPUTER_DELEGATE
# define ACACIA_ENABLE_IOS_PRECOMPUTER_DELEGATE 0
#endif
#ifndef ACACIA_ENABLE_IOS_PRECOMPUTER_FAKE_VARS
# define ACACIA_ENABLE_IOS_PRECOMPUTER_FAKE_VARS 0
#endif
#ifndef ACACIA_ENABLE_IOS_PRECOMPUTER_POWSET
# define ACACIA_ENABLE_IOS_PRECOMPUTER_POWSET 0
#endif
#ifndef ACACIA_ENABLE_IOS_PRECOMPUTER_STANDARD
# define ACACIA_ENABLE_IOS_PRECOMPUTER_STANDARD 1
#endif
#ifndef ACACIA_ENABLE_IOS_PRECOMPUTER_MONA
# define ACACIA_ENABLE_IOS_PRECOMPUTER_MONA 0
#endif

#ifndef ACACIA_ENABLE_ACTIONER_NO_IOS_PRECOMPUTATION
# define ACACIA_ENABLE_ACTIONER_NO_IOS_PRECOMPUTATION 0
#endif
#ifndef ACACIA_ENABLE_ACTIONER_STANDARD
# define ACACIA_ENABLE_ACTIONER_STANDARD 1
#endif

#ifndef ACACIA_ENABLE_INPUT_PICKER_CRITICAL
# define ACACIA_ENABLE_INPUT_PICKER_CRITICAL 0
#endif
#ifndef ACACIA_ENABLE_INPUT_PICKER_CRITICAL_FULLRND
# define ACACIA_ENABLE_INPUT_PICKER_CRITICAL_FULLRND 0
#endif
#ifndef ACACIA_ENABLE_INPUT_PICKER_CRITICAL_PQ
# define ACACIA_ENABLE_INPUT_PICKER_CRITICAL_PQ 1
#endif
#ifndef ACACIA_ENABLE_INPUT_PICKER_CRITICAL_RND
# define ACACIA_ENABLE_INPUT_PICKER_CRITICAL_RND 0
#endif

#include "config/derived_gates.hh"
#include "config/validate.hh"

#ifdef NO_SIMD
# pragma message("Compiling without SIMD")
# ifndef ARRAY_IMPL
#  define ARRAY_IMPL array_backed_sum
# endif
# ifndef VECTOR_IMPL
#  define VECTOR_IMPL vector_backed
# endif
#else
# pragma message("Compiling with SIMD")
# ifndef ARRAY_IMPL
#  define ARRAY_IMPL simd_array_backed_sum
# endif
# ifndef VECTOR_IMPL
#  define VECTOR_IMPL simd_vector_backed
# endif
#endif

#ifndef ARRAY_AND_BITSET_DOWNSET_IMPL
# define ARRAY_AND_BITSET_DOWNSET_IMPL vector_backed
#endif
#ifndef VECTOR_AND_BITSET_DOWNSET_IMPL
# define VECTOR_AND_BITSET_DOWNSET_IMPL vector_backed
#endif
