name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install packages
      run: |
        sudo apt-get -y install zsh git gcc python-is-python3 meson ninja-build gnupg wget python3-pip python3-distutils pkg-config libglib2.0-dev libffi-dev libboost-dev autoconf automake libtool bison flex valgrind
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/setup-python@v5
    - name: Install python dependencies
      run: |
        pip install pygraph
    - name: Compile all configurations
      run: |
        ./self-benchmark.sh -R
    - name: Run basic benchmark with low timeout as test
      run: |
        ./self-benchmark.sh -b ab/set1 -t 0.5
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-logs
        path: _bm-logs/
    - name: Upload compilation logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: meson-logs
        path: build_base/meson-logs
