# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: debian:sid
    steps:
    - name: Install packages
      run: |
        apt-get -y update
        apt-get -y install zsh git gcc python-is-python3 meson ninja-build gnupg wget python3-pip python3-distutils pkg-config libglib2.0-dev libffi-dev libboost-dev autoconf automake libtool bison flex valgrind
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-python@v2
    - name: Install python dependencies
      run: |
        pip install pygraph --break-system-packages
    - name: Compile all configurations
      run: |
        ./self-benchmark.sh -R
    - name: Run basic benchmark with low timeout as test
      run: |
        ./self-benchmark.sh -b ab/set1 -t 0.5
    - name: Upload test results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test-logs
        path: _bm-logs/
    - name: Upload compilation logs
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: meson-logs
        path: build_base/meson-logs
