# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: debian:sid
    steps:
    - name: Install packages
      run: |
        apt-get -y update
        apt-get -y install zsh git gcc python meson ninja-build gnupg wget python3-pip pkg-config libglib2.0-dev libffi6 libboost-dev autoconf automake libtool
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - uses: actions/setup-python@v1
    - name: Install python dependencies
      run: |
        pip install pygraph
    - uses: BSFishy/meson-build@v1.0.1
      with:
        setup-options: --buildtype=release
        action: test
        options: --suite=ab/tiny --suite=ab/small
    - name: Upload test results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test-log
        path: build/meson-logs/
