name: CI
on:
  push:
    branches:
      - master
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install packages
      run: |
        sudo apt update
        sudo apt install -y zsh meson git g++-14 python-is-python3 \
                    ninja-build gnupg wget python3-pip \
                    pkg-config libffi-dev \
                    libtool valgrind gpg
        sudo pip install --upgrade meson
    - name: Install newer libltldl
      run: |
        sudo wget http://launchpadlibrarian.net/815947228/libltdl7_2.5.4-4build1_amd64.deb
        sudo dpkg -i libltdl7_2.5.4-4build1_amd64.deb
        sudo apt -f install
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install Spot
      run: |
        sudo wget http://www.lre.epita.fr/dload/spot/spot-2.14.4.tar.gz
        tar -xvzf spot-2.14.4.tar.gz
        cd spot-2.14.4
        sudo ./configure --enable-max-accsets=64 --disable-python
        sudo make
        sudo make install
    - name: Compile and test a debug configuration
      run: |
        export CXX=g++-14
        ./self-benchmark.sh -c base -j -b ab/tiny
        meson test -C build_base --suite ab/small
        meson test -C build_base --suite ab/issue54
    - name: Compile and test all configurations
      run: |
        export CXX=g++-14
        ./self-benchmark.sh -j -b ab/tiny
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-logs
        path: _bm-logs/
    - name: Upload compilation logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: meson-logs
        path: build_base/meson-logs
